name: 自动采集proxy

on: 
  # schedule: #UTC+0               #UTC+8
  #   - cron: '*/35 0-8 * * 1-5'   #工作日 上午8:00 - 下午4:00
  #   - cron: '*/25 8-14 * * 1-5'  #工作日 下午4:00 - 晚上10:00
  #   - cron: '*/55 14-21 * * 1-4' #工作日 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 21-23 * * 1-5' #工作日 次日凌晨5:00 - 次日上午8:00
  #   - cron: '*/25 14-21 * * 5'   #星期五 晚上10:00 - 次日凌晨5:00
  #   - cron: '*/25 * * * 0,6'     #休息日 全天候
  # repository_dispatch: #https://www.chenshaowen.com/blog/how-to-trigger-github-action-remotely.html
    # types:
      # - Webhook
  workflow_dispatch: #手动调试按钮

jobs: 
  my-job: 
    name: Max Job
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3     #git clone
    - uses: actions/setup-node@v3   #Node.js环境
      with:
        node-version: '16.x'        #Node.js 16.x
    - uses: actions/setup-python@v4 #python环境
      with:
        python-version: '3.x'       #python 3.x
        cache: 'pip'                #pip cache
    - name: Timezone #UTC+0 → UTC+8
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git
      run: | #配置git的上传用户名和邮箱
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: 安装依赖
      run: |
        pip install -r requirements.txt
    - name: 执行任务
      run: |
        python main2.py
         
    - name: git push
      run: ./.github/update-repo.sh || true
